# Generated by Django 5.2.7 on 2026-05-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['name'], name='core_medici_name_dfd7d8_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['category'], name='core_medici_categor_cf6e69_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['price'], name='core_medici_price_2e3653_idx'),
        ),
    ]
